### ISSUE TITLE
org.idpass:idpass-smartscanner:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by ErsinDemirbas** [idpass/smartscanner-core#107]
org.idpass:idpass-smartscanner:0.0.1-SNAPSHOT not working. Is there any way to import this repo now?

**Comment by rjmangubat23** [comment]
hello @ErsinDemirbas we are still working on that issue. 

In the meantime can you please follow our guide from wiki in [Building from source](https://github.com/idpass/smartscanner-core/wiki/Building-from-source). 

If successfully built you can generate an `.aar` file which you can then use. Thank you!

**Comment by ErsinDemirbas** [comment]
Thanks for your response, by the way I need your help. I wonder that when I use  `ImageCapture.Builder().setTargetRotation(Surface.ROTATION_180)` the captured image is roteted but mrz reader area is in top of the surface so to scan a card I have to show mrz to top of the scanner area.
 So how this mrz scanner rotate as image. Sorry for my bad English. Thanks advance.

**Comment by ErsinDemirbas** [comment]
I solve this problem by don't crop image in MRZAnalyzer.kt. Will this make a problem in the feture scans?
