### ISSUE TITLE
Allow Access to All Files

### ISSUE THREAD

**Issue by ErsinDemirbas** [idpass/smartscanner-core#109]
Hello, how to remove this 'allow access to all files' request from app? (Version 0.3.3)

**Comment by rjmangubat23** [comment]
@ErsinDemirbas we are currently using the storage permission to store the image after a successful scan. For this, you will have to modify the existing permissions that concern `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE`.

**Comment by ErsinDemirbas** [comment]
Thank you so much 👍
