### ISSUE TITLE
Downloading OCR models. Please wait...

### ISSUE THREAD

**Issue by Mojtaba-Shafaei** [idpass/smartscanner-core#110]
## Downloading OCR models. Please wait..."

When opening the MRZ scanning, this message ("Downloading OCR models. Please wait...") appears in the center of the screen after 5 minutes it changed to "Processing OCR models. PLease wait...". I kept it running for 10 minutes but nothing happened

## Steps to Reproduce the Problem

1. clone the repository, and check out the tag 0.3.7
2. run the application
3. press MRZ scanner

- Version: 3.0.7
![photo_2021-11-01_20-51-29](https://user-images.githubusercontent.com/12367513/139713052-d0e99ad1-5a82-4446-877f-8fe4f4d9a503.jpg)
![photo_2021-11-01_20-51-34](https://user-images.githubusercontent.com/12367513/139713131-dd0a9612-935a-4fc9-ac4b-d1da5e76b944.jpg)

**Comment by rjmangubat23** [comment]
Hello @Mojtaba-Shafaei may we ask what phone did you use? 

In the mean time can you please check if `Google Play Services` is on the latest updated version and then try to checkout `develop` branch and run the app from there.

**Comment by Mojtaba-Shafaei** [comment]
I have a moto g 5G plus (XT2075-3) android 11, I have the latest version of play service. I'm testing it again and will inform you

**Comment by rjmangubat23** [comment]
Will be addressed via https://github.com/idpass/smartscanner-core/issues/116 on this branch: https://github.com/idpass/smartscanner-core/tree/feature/text-recognition-v2
