### ISSUE TITLE
QR code : It takes much amount of time to scan hard copy of ID 

### ISSUE THREAD

**Issue by dhruvsonagara** [idpass/smartscanner-core#117]
While using the intent call in ODK it should scan the QR code easily but in my case it takes so much amount of time
 

It should scan the QR code in just friction of seconds and give the desired result with hardcopy also in same time

I was using Samsung Galaxy A70s where I faced this issue with intent call in ODK collect app.

- Version: 0.3.10

**Comment by jeremi** [comment]
@rjmangubat23 can it be an autofocus issue? 
Is it part of the fix we did recently?

**Comment by rjmangubat23** [comment]
@jeremi yes I believe so and should be. 

@dj2718 thank you for pointing this out. 😄 

We recently did a fix for this, can you please try the build linked below? 
[idpass-smartscanner-0.3.11-19-8b04c79-feature_text-recognition-v2.apk](https://drive.google.com/file/d/16jrdnIS_JU9lZuKkpzRclwzd0X64tOZy/view?usp=sharing
)

The latest fixes are not merged to `develop` yet but can be found in: https://github.com/newlogic/smartscanner-core/tree/mlkit-v2

**Comment by dhruvsonagara** [comment]
@rjmangubat23 @jeremi New version you shared works as expected and I will try that out with the hard copy of ID
