### ISSUE TITLE
Failed to resolve: org.idpass:smartscanner-android-api:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Fanom2813** [idpass/smartscanner-core#119]
Android studio isn't able to resolve

**Comment by rjmangubat23** [comment]
hello @Fanom2813 👋 

Please note that this is still currently unavailable as we are still working on adding this to mavenCentral. 

In the meantime what you can do as a work around is by building aars and adding it directly to your own project:

1. Clone repo and checkout `develop` branch 
2. Open in Android Studio and in `Gradle` tab go to `idpass-smart-scanner>core-lib>Tasks>build>assemble` or you can build it via terminal: `./gradlew assemble` 
3. Import newly built aar file which can be found in `core-lib/build/outputs`  via this  [guide](https://www.androidbugfix.com/2021/12/how-to-import-aar-module-on-android.html) into your project 
4. Don't forget to add MLKit dependencies: https://developers.google.com/ml-kit/vision/text-recognition/v2/android
5. Build your android project and it will be ready for your usage.

**Comment by nicholemnl** [comment]
This has been resolved in https://github.com/newlogic/smartscanner-core/pull/125 together with #124
