### ISSUE TITLE
Problems with project compilation -- missing signing.properties

### ISSUE THREAD

**Issue by IvyMasterDiego** [idpass/smartscanner-core#122]
## Current behavior

I can't compile the project correctly, it shows me the error:
`signing.properties (The system cannot find the file specified)`

## Context

I really just clone the project and try to compile it and it won't let me.

**Comment by rjmangubat23** [comment]
Hello @IvyMasterDiego! 👋🏻 

Please note that we chose not to commit our `signing.properties` file for security reasons.

1. So you will have to create your own keystore named `upload-keystore` and overwrite the existing one we have. 
- To create your own --> https://developer.android.com/studio/publish/app-signing#generate-key

2. Create your own `signing.properties` file containing the following below:

```
STORE_PASSWORD=yourkeystorepass
KEY_ALIAS=projectkeyalias
KEY_PASSWORD=keyaliaspassword
```

Then try to rebuild and compile. 🙏🏻

**Comment by IvyMasterDiego** [comment]
Ok, I'll try and see, thanks. :)
