### ISSUE TITLE
Add truncated PDF417 support 

### ISSUE THREAD

**Issue by rjmangubat23** [idpass/smartscanner-core#123]
## Current Behaviour

Not being able to scan truncated PDF417 due to lack of MLKit Support 
See: 
- https://github.com/googlesamples/mlkit/issues/175

- https://issuetracker.google.com/issues/247450973?pli=1

## Expected Behaviour

scan truncated PDF417 successfully

## Context

- Will look into zxing libraries for better support

**Comment by nicholemnl** [comment]
This has been resolved in this PR https://github.com/newlogic/smartscanner-core/pull/128
