### ISSUE TITLE
Manifest and ScaleType error

### ISSUE THREAD

**Issue by emredg** [idpass/smartscanner-core#124]
First of all i followed that issue and installed the lib: https://github.com/newlogic/smartscanner-core/issues/119

(I created signing.properties file by myself)

After that i create a file in my project and moved the smartscannerlib-release.aar file to there. And added this line t o my gradle file: 
`implementation files('../smartscanner/smartscannerlib-release.aar')`

And when i just sync the gradle and build it, i got error.

`Manifest merger failed : Attribute application@theme value=(@style/Theme.ASM) from AndroidManifest.xml:33:9-41
	is also present at [smartscannerlib-release.aar] AndroidManifest.xml:30:9-40 value=(@style/AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:24:5-97:19 to override.`
	
I googled it and tried to add this line to my manifest:
`tools:replace="android:theme"`

After that i tried to build but that now i got that error:
`ERROR:/Users/buhesapsenin/.gradle/caches/transforms-3/52c64db2506c28514c63ed34a2dfc384/transformed/jetified-smartscannerlib-release/res/layout/activity_smart_scanner.xml:77: AAPT: error: attribute scaleType (aka com.kendineiyibak.app:scaleType) not found.`

I deleted items in that xml's contraint layout, and tried to compile with clean xml but same i got same error. I think It's not about that xml.

Can u help me?

**Comment by nicholemnl** [comment]
Hello thank you for sending your issue. I think I also have experience this but should be fix in this branch [hotfix/mrz-improvement](https://github.com/newlogic/smartscanner-core/tree/feature/jwt-integration)

Changes : 
https://github.com/newlogic/smartscanner-core/commit/fed968a7527eda645e440156f39f016173ad7f66

Once the last PR https://github.com/newlogic/smartscanner-core/pull/125 merged we can close this.
