### ISSUE TITLE
Ability to read JWT token via QR Code

### ISSUE THREAD

**Issue by rjmangubat23** [idpass/smartscanner-core#127]
## Context

- Add scanning for QR Codes that contain JWT tokens
- Ability to decode and verify a signature
- Update display response
- Additional: Load JWT configuration as QR code in Settings screen

## Specs
- Scan QR code with JWT configuration
   - After scannig a QR code, it should redirect to the settings page
   - It will replace the current setting configuration `"Profile name"` and `"Public Key"`
   - A toast (popup info) information will show up saying `"Configuration loaded successfully"`
- Scan QR code with JWT payload
   - Must validate that the public key to decode JWT, otherwise it throws error saying `"Error: Signature verification failed. Please ensure a configuration profile was loaded"`
   - If success, it should show a list of key/values pair payload
   - If the button `"Show raw result"` is tapped, it will display the raw result page
- Scan QR code without JWT payload
   - It will show the raw result page
   
   

## Reference
Designs https://www.figma.com/file/olRF7LbcmADK0M3x3ytYNd/%5BSCOPE-174066%5D-ID-Pass-SmartScanner---Newlogic?node-id=0%3A1

Test Sample https://docs.google.com/document/d/12LAht16BKgov-7jSlvDktbZxoCG6g58cSIHz0lhaP4I/edit?usp=sharing

Test Sample 2 https://docs.google.com/document/d/1NWWSbEibXYEMnMleKP0LFKd3vlOACZM5xgJGJxTUNdA/edit?usp=sharing

**Comment by nicholemnl** [comment]
Additional to fix :
- Overlap config in the settings page bottom is overlapping views for smaller screen android
![image (6)](https://user-images.githubusercontent.com/101313323/203486087-c30af4f7-66d8-4180-8fc0-39cba48f7ff2.png)

- API for QRcode is not ready for integration
