### ISSUE TITLE
Add a way to Scan a QR Code that contain a Gziped JSON

### ISSUE THREAD

**Issue by jeremi** [idpass/smartscanner-core#21]
This would be available only through another app that calls using intent. 
For QR Code scanning, we should be able to have those options:
- gzipped (true or false)
- json (true or false)
- Json path (to get 1 value in a json file)

return in the intent:
- qr_code_text
- qr_code_json_value (the target value of the json path)

Lib:
https://github.com/json-path/JsonPath

**Comment by rjmangubat23** [comment]
Sample Gzipped QR Code:
![image](https://user-images.githubusercontent.com/11598375/104156504-2a4a4b80-5424-11eb-8034-8ae3e33b9d64.png)

**Comment by rjmangubat23** [comment]
Hello @jeremi please see PRs for this issue: 

https://github.com/idpass/smartscanner-core/pull/37 Add a way to Scan a QR Code that contain a Gziped JSON 
https://github.com/idpass/smartscanner-android/pull/3 Update SmartScanner api for QR Codes that contain a Gziped JSON
