### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jeremi** [idpass/smartscanner-core#26]
Start documenting the project

**Comment by arnellebalane** [comment]
@jeremi @elahonoridez I've added an [initial PR](https://github.com/idpass/idpass-smart-scanner-core/pull/29) to improve the documentation provided in the README.

From here I'll work with @rjmangubat23 for the complete [API Reference](https://github.com/idpass/idpass-smart-scanner-core/wiki/API-Reference) and [Result fields reference](https://github.com/idpass/idpass-smart-scanner-core/wiki/Result-fields-reference) pages.
