### ISSUE TITLE
Fix bounding box for ID PASS Lite

### ISSUE THREAD

**Issue by rjmangubat23** [idpass/smartscanner-core#30]
When scanning ID PASS Lite QR Code, the bounding box does not correspond to where the QR code should be

**Comment by elahonoridez** [comment]
Tests run on 08 January 2021 at 5:50 PM PH timezone

**VERIFICATION:**
- Able to install the App with the test build **_idpass-smartscanner-debug-2000_01082021_1640.apk_**
- Able to open or use the **ID PASS Lite** feature
- Able to capture the QR Code in the sample image **/florence_idpass.svg** and results with data were loaded in the page.
<img src="https://user-images.githubusercontent.com/75471103/104003870-e24edd00-5207-11eb-902e-2cd5467501ff.jpg" width="300" height="600">

- Tried placing the device's camera closer to the sample QR Code Image.
<img src="https://user-images.githubusercontent.com/75471103/104003996-14603f00-5208-11eb-8388-6c5d07d5b5f1.jpg" width="300" height="600">

Sample of the Scan Results Page shown in the image below:
![Screenshot_20210108-224812_SmartScanner](https://user-images.githubusercontent.com/75471103/104004140-4376b080-5208-11eb-8e1e-773372ab0375.jpg)

- Run minor stress testing by repeating step 4 for 5 times only.

**VALIDATION:**
The feature consistently works even when the device's camera which is used to capture the code or for scanning is placed closer or very close to the QR Code image.
