### ISSUE TITLE
Find a way if NFC Passport have RTL/LTR embedded locale details

### ISSUE THREAD

**Issue by rjmangubat23** [idpass/smartscanner-core#61]
## Current Behaviour

Force app to define if Scanner uses RTL/LTR via `nfcLocale` in ScannerOptions 

## Expected Behaviour

Find a way if NFC Passport have RTL/LTR embedded locale details

**Comment by typelogic** [comment]
The e-passport's content data structure and encoding is via `ASN.1/BER TLV`. The issue of `directionality` whether a displayable string is `right-to-left` or `left-to-right` can be deduced via the string content itself. There is no dedicated field that can determine this directionality. 

The spec specified the use of `Unicode / UTF-8` in the encoding of data element contents using national characters. The content string itself can be used for the determination of directionality:

```java
/**
 * Determine if String s is right-to-left or RTL.
 * Example of RTL languages: Arabic, Hebrew, etc
 */
private boolean isRTL(String s) {
    for (int i = 0; i < s.length(); i++) {
        byte d = Character.getDirectionality(s.charAt(i));
        if (d == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
            d == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC ||
            d == Character.DIRECTIONALITY_RIGHT_TO_LEFT_EMBEDDING ||
            d == Character.DIRECTIONALITY_RIGHT_TO_LEFT_OVERRIDE
        ) {
            return true;
        }
    }

    return false;
}
```

**Comment by rjmangubat23** [comment]
okay thank you closing this issue as current solution is proper workaround.
